<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

?>
<h3><?php esc_html_e( 'Header', 'genesis' ); ?></h3>
<p>
	<?php
	/* translators: Open and close strong tags. */
	printf( esc_html__( 'The %sDynamic text%s option will use the Site Title and Site Description from your site\'s settings in your header.', 'genesis' ), '<strong>', '</strong>' );
	?>
</p>
<p>
	<?php
	/* translators: Open and close strong tags. */
	printf( esc_html__( 'The %sImage logo%s option will use a logo image file in the header instead of the site\'s title and description. This setting adds a .header-image class to your site, allowing you to specify the header image in your child theme\'s style.css. By default, the logo can be saved as logo.png and saved to the images folder of your child theme.', 'genesis' ), '<strong>', '</strong>' );
	?>
</p>
